---
- name: Enforce Windows identity compliance
  hosts: all
  gather_facts: false

  tasks:
    - name: Ensure Ansible service account is in local Administrators
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - 'COMPANYNET\HTSGLBAnsibleSVC01'
        state: present

    - name: Update hetwinadmin password from rotated Key Vault secret
      ansible.windows.win_user:
        name: hetwinadmin
        password: "{{ hetwinadmin_password }}"
        update_password: always
      no_log: true