---
- name: Add Ansible service account to local Administrators
  hosts: all
  gather_facts: false

  tasks:
    - name: Ensure Ansible service account is in local Administrators
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - "COMPANYNET\\HTSGLBAnsibleSVC01"
        state: present